apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /run/desktop/mnt/host/Users/danielgarcia/Documents/Master\ of\ Information\ Technology/2024/T1/Cloud\ Native\ Application\ Development/Mapped\ Persistent\ Volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop