apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  externalTrafficPolicy: Cluster
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 27017
  type: LoadBalancer