services:
  server:
    image: australia-southeast2-docker.pkg.dev/sit737-24t1-garcia-var-ade6d59/sit737/calculator:1.0.0
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3010:3010
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3010/add?num1=3&num2=4"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure
