apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
  labels:
    app: calculator-api
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-api
  template:
    metadata:
      labels:
        app: calculator-api
        tier: backend
    spec:
      containers:
      - name: calculator-api
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/sit737-24t1-garcia-var-ade6d59/calculator-api/calculator-api:1.0.0
        ports:
        - containerPort: 3010
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              key: username
              name: mongodb-config
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mongodb-secret
