apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-api
  labels:
    app: calculator-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: calculator-api
        imagePullPolicy: Never
        image: australia-southeast2-docker.pkg.dev/sit737-24t1-garcia-var-ade6d59/sit737/calculator:latest
        ports:
        - containerPort: 3010