name: Build and Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: 'cluster-1'
  GKE_ZONE: 'us-central1-a'
  CONTAINER_REGISTRY_URI: 'us-central1-docker.pkg.dev/sit737-24t1-garcia-var-ade6d59/calculator-api/calculator-api'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup gcloud CLI
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        project_id: ${{ env.PROJECT_ID }}
        version: 'latest'

    # Build the Docker image
    - name: Build
      run: |-
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        IMAGE_URI=$CONTAINER_REGISTRY_URI:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV